check:
    global:
        statements: 10
        lines: 10
        branches: 10
        functions: 10
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
