check:
    global:
        statements: 70
        lines: 70
        branches: 70
        functions: 70
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
