export const  ATypes = {
    GOT_URI: "GOT_URI",
    GOT_SESION_SUCCESS: "GOT_SESION_SUCCESS",
    GOT_SESION_LOADING: "GOT_SESION_LOADING",
    GOT_SESION_ERROR: "GOT_SESION_ERROR",
    USER_SELECTED: "USER_SELECTED",
    GOT_USERS: "GOT_USERS",
    GOT_MESSAGES: "GOT_MESSAGES",
    SEARCH_FILTER_CHANGED: "SEARCH_FILTER_CHANGED",
    SERVER_TRANSACTION_TIMESTAMP: "SERVER_TRANSACTION_TIMESTAMP"
}
