export const  ATypes = {
    GOT_URI: "GOT_URI",
    GOT_SESSION_SUCCESS: "GOT_SESSION_SUCCESS",
    GOT_SESSION_RELOADING: "GOT_SESSION_RELOADING",
    GOT_SESSION_LOADING: "GOT_SESSION_LOADING",
    GOT_SESSION_ERROR: "GOT_SESSION_ERROR",
    USER_SELECTED: "USER_SELECTED",
    GOT_USERS: "GOT_USERS",
    GOT_MESSAGES: "GOT_MESSAGES",
    SEARCH_FILTER_CHANGED: "SEARCH_FILTER_CHANGED",
    SERVER_TRANSACTION_TIMESTAMP: "SERVER_TRANSACTION_TIMESTAMP",
    GOT_CONVERSATIONS: "GOT_CONVERSATIONS",
    CONVERSATION_SELECTED: "CONVERSATION_SELECTED",
    CONVERSATION_CREATED: "CONVERSATION_CREATED",
    GOT_CONVERSATION_DETAIL_SUCCESS: "GOT_CONVERSATION_DETAIL_SUCCESS"
}
