export const  ATypes = {
    GOT_URI: "GOT_URI",
    GOT_SESION: "GOT_SESION",
    USER_SELECTED: "USER_SELECTED",
    GOT_USERS: "GOT_USERS",
    GOT_MESSAGES: "GOT_MESSAGES",
    SEARCH_FILTER_CHANGED: "SEARCH_FILTER_CHANGED" 
}
